# Generated by Django 5.1.6 on 2025-03-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='applicable_menus',
            field=models.ManyToManyField(blank=True, help_text='ถ้าเว้นว่างหมายถึงโปรโมชั่นใช้ได้กับทุกเมนู', related_name='promotions', to='myapp.menu'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='usage_limit',
            field=models.PositiveIntegerField(default=0, help_text='จำนวนครั้งที่ใช้ได้ (0 หมายถึงไม่จำกัด)'),
        ),
    ]
