# Generated by Django 5.1.6 on 2025-03-02 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_promotion_applicable_menus_promotion_usage_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="member",
        ),
    ]
